# terminal color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# do not rename windows
set -g allow-rename off

# shorten delay
set -sg escape-time 1

# scrollback buffer
set -g history-limit 100000

# vim-style in copy mode
setw -g mode-keys vi

set -g mouse on

# no status line
set -g status off

# Ensure tmux allows applications to set the clipboard
set -s set-clipboard on

# Trigger copy-mode with 'v' and copy to system clipboard with 'y'
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection

# Copy with mouse, but STAY in copy mode (don't jump to bottom)
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection

