# Set locale
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Run `brew install` without auto update
export HOMEBREW_NO_AUTO_UPDATE=1

# PATH {
# mac: /ect/paths.d and /etc/paths are first exported to PATH
# ubuntu: /ect/login.def/ENV_PATH is first exported to PATH

if [ "$(uname)" = "Darwin" ]; then
    if [ "$(uname -m)" = "x86_64" ]; then
        brew_prefix="/usr/local"
    else
        brew_prefix="/opt/homebrew"
    fi
    PATH="$brew_prefix/bin:$PATH"
    PATH="$brew_prefix/sbin:$PATH"

    # For visual code
    PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"

    PATH=$PATH:$HOME/.toolbox/bin

    export OpenCV_DIR="$brew_prefix/opt/opencv@4/share/OpenCV"
    export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home

    # >>> conda initialize >>>
    # !! Contents within this block are managed by 'conda init' !!
    __conda_setup="$('$HOME/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "$HOME/miniforge3/etc/profile.d/conda.sh" ]; then
            . "$HOME/miniforge3/etc/profile.d/conda.sh"
        else
            export PATH="$HOME/miniforge3/bin:$PATH"
        fi
    fi
    unset __conda_setup
    # <<< conda initialize <<<

fi

# Amazon toolbox
PATH="$HOME/.toolbox/bin:$PATH"

# Remove duplicates
PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"

# Export to child processes
export PATH
# }

# Alias {
alias c='clear'
alias cfi='clang-format -i'
alias dc='docker-compose'
alias gco='git checkout'
alias gd='git diff'
alias glog='git log --pretty=oneline --graph --decorate --abbrev-commit'
alias gpr='git pull --rebase'
alias gs='git status'
alias gtr='cd `git rev-parse --show-toplevel`'
alias kc='kubectl'
alias kcei='kubectl exec -it'
alias kcgp='kubectl get pod'
alias kcgs='kubectl get svc'
alias kclf='kubectl logs -f'
alias py='python3'

alias bb='brazil-build'
alias bws='brazil ws'
alias crd='cr --description ~/.crdescription '
# }

# Autojump {
if [ "$(uname)" = "Darwin" ] ; then
    aj_sh="${brew_prefix}/etc/profile.d/autojump.sh"
else
    aj_sh="/usr/share/autojump/autojump.sh"
fi
[ -f ${aj_sh} ] && . ${aj_sh}
# }

# Editor {
EDITOR=vim
VISUAL=vim
# }

# Vim {
alias ev='vim $HOME/.vimrc'
alias ez='vim $HOME/.zshrc'
alias v=vim
alias vi=vim
alias vil='vim -u NONE -c "set nu|set cursorline|set nowrap"'
# }

# Oh-my-zsh {
# less search highlight, so: standout begin se: standout end
export LESS_TERMCAP_so=$'\E[30;43m'
export LESS_TERMCAP_se=$'\E[0m'

HYPHEN_INSENSITIVE=true
ZSH=$HOME/.oh-my-zsh
ZSH_DISABLE_COMPFIX=true
ZSH_THEME="robbyrussell"
source $ZSH/oh-my-zsh.sh

# Setup PROMPT
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}(%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
if [ "$(uname)" = "Darwin" ]; then
    PROMPT='%{$fg[cyan]%}%3~%{$reset_color%}$(git_prompt_info) %# '
else
    PROMPT='%{$fg[magenta]%}%m:%{$fg[cyan]%}%3~%{$reset_color%}$(git_prompt_info) %# '
fi
# }

# vim: fdm=marker fmr={,}
